[package]
name = "srx"
version = "0.1.0"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false